services:
  - type: web
    name: aiRecord
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run streamlit_app.py --server.port=$PORT --server.enableCORS=false"
